title: Programming Docs
description: Some Programming-Examples with Explanation.
theme: just-the-docs

url: https://dunjawohlers.github.io/knowledgebase/

aux_links:
  Template Repository: https://dunjawohlers.github.io/knowledgebase/

color_scheme: dark

heading_anchors: false
